export { default as Header } from "./Header";
export { default as Home } from "./Home";
export { default as Learning } from "./Learning";
export { default as Quiz } from "./Quiz";
export { default as Results } from "./Results";
export { default as Loader } from "./Loader";
export { default as About } from "./About";
export { default as Error } from "./Error";
export { default as Footer } from "./Footer";
